config/routes.rb
Rails.application.routes.draw do

  root 'books#top'
  get 'home/about' => 'books#about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true

  validates :body,
    presence: true,
    length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,
    presence: true,
    length: { minimum: 2, maximum: 20 }

  validates :introduction,
    length: {maximum: 50}

  has_many :books, dependent: :destroy

  attachment :profile_image



  def email_changed?
   false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

  def after_sign_in_path_for(resource)
    flash[:sign_in] = "Signed in successfully"
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    flash[:sign_out] = "Signed out successfully."
    root_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:show, :index, :edit]

  def about
  end

  def top
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:create] = "Book was successfully created"
      redirect_to book_path(@book.id)
    else
      @user = User.find(current_user.id)
      @books = Book.all.page(params[:page]).reverse_order
      @newbook = @book
      render :index
    end
  end

  def index
    @user = User.find(current_user.id)
    @books = Book.all.page(params[:page]).reverse_order
    @newbook = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @book_user = User.find(@book.user_id)
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:update] = "Book was successfully updated"
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @users = User.all.page(params[:page]).reverse_order
  end

  def show
    @book = Book.new
    @book_user = User.find(params[:id])
    @books = @book_user.books.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:update] = "You have updated user successfully"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/about.html.erb
<%= render 'layouts/nav', user: @user %>
<div class="body">
  <div class="container">
          <p id="notice"></p>
          <h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/books/edit.html.erb
<%= render 'layouts/nav', user: @user %>
<div class="body">
  <div class="container">
    <p id="notice"></p>
    <div class="row">
      <div class="col-xs-6 col-xs-offset-3">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <ul>
            <% @book.errors.full_messages.each do |msg| %>
              <li>error</li>
              <li><%= msg %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_for(@book) do |f| %>
          <div class="field row">
            <label for="book_title">Title</label>
             <%= f.text_field :title , class: "col-xs-12 book_title" %>
          </div>

          <div class="field row">
            <label for="book_body">Body</label>
            <%= f.text_area :body, class: "col-xs-12 book_body" %>
          </div>

          <div class="actions row">
            <%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
          </div>
        <% end %>
        <%= link_to  'Show' , book_path(@book.id) %>
        |
        <a href='/books'>Back</a>
      </div>
      <div class="col-md-3"></div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/nav', user: @user %>
<div class="body">
  <div class=container>
    <div class="row">
      <%= render 'layouts/profile', user: @user, book: @newbook %>
      <div class="col-xs-9">
        <h2>Books</h2>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Body</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60,  fallback: "no_image.jpg"%>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
            <%= paginate @books, class: "paginate" %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= render 'layouts/nav', user: @user %>
<div class="body">
  <div class=container>
    <%= flash[:create] %>
    <%= flash[:update] %>
    <div class="row">
      <%= render 'layouts/profile', user: @book_user, book: @newbook %>
      <div class="col-xs-9">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
              <tr>
                <td></td>
                <td>
                  <%= link_to user_path(@book_user.id) do %>
                    <%= attachment_image_tag @book.user, :profile_image, :fill, 30, 30, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
                    <%= @book_user.name %>
                  <% end %>
                </td>
                <td><%= @book.title %></td>
                <td><%= @book.body %></td>
            　　 <% if @book.user.id == current_user.id %>
                  <td><%= link_to "Edit", edit_book_path(@book) %></td>
                  <td><%= link_to "Destroy", book_path(@book.id), method: :delete, data: {confirm: "本当に消しますか?"} %></td>
                <% end %>
              </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/books/top.html.erb
<%= render 'layouts/nav', user: @user %>
<div class="body">
  <div class="container">
    <%= flash[:sign_out] %>
    <div class="row">
      <div class="top-message col-md-offset-3 col-md-6">
        <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
        <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper">
          <div class="row">
            <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
          </div>
          <div class="row">
            <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
    <nav>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li ><%= link_to  ' Home' , user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>
          <li><a class="glyphicon glyphicon-user users" href="/users"> Users</a></li>
          <li><a class="glyphicon glyphicon-book books" href="/books"> Books</a></li>
          <li><a class="glyphicon glyphicon-log-out logout" rel="nofollow" data-method="delete" href="/users/sign_out"> logout</a></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><a class="glyphicon glyphicon-home home" href="/"> Home</a></li>
          <li><a class="glyphicon glyphicon-user users" href="/home/about"> About</a></li>
          <li><a class="glyphicon glyphicon-book books" href="/users/sign_up"> sign up</a></li>
          <li><a class="glyphicon glyphicon-log-out logout" rel="nofollow" href="/users/sign_in"> login</a></li>
        </ul>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/_profile.html.erb
<div class="col-xs-3">
  <h2>User info</h2>
  <div class="form-group has-icon">
      <div class="user-edit-image">
        <%= attachment_image_tag @user, :profile_image, :fill, 30, 30, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
      </div>
      <label class="control-label sr-only" for="inputEmail">ProfileImage</label>

  </div>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <%= link_to edit_user_path(user.id) do %>
      <p class= "col-xs-12 btn btn-default glyphicon glyphicon-wrench "></p>
    <% end %>
  </div>


  <h2>New book</h2>
  <% if book.errors.any? %>
    <ul>
      <% book.errors.full_messages.each do |msg| %>
        <li>error</li>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_with model: book, url: user_registration_path do |f| %>
    <div class="field row">
      <h4>Title</h4>
      <div class="col-xs-12 book_title">
        <%= f.text_field :title %>
      </div>
      </div>
      <div class="field row">
       <h4>Body</h4>
      <div class="col-xs-12 book_body">
        <%= f.text_area :body %>
      </div>
    </div>
    <div>
      <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booker2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= render 'layouts/nav', user: @user %>
<div class="body">
  <div class="container">
    <%= flash[:update] %>
    <h2>User info</h2>
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li>error</li>
            <li><%= msg %></li>
          <% end %>
        </ul>
      <% end %>
      <% f.email_field :email %>
      <div class="field">
        <label for="user_name">Name</label>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <label for="user_image">Image</label>
        <%= f.attachment_field :profile_image, placeholder: "ファイルを選択", class: "user-edit-form" %>
      </div>
      <div class="field">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction %>
      </div>
      <div class="actions">
        <%= f.submit "Update User" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'layouts/nav', user: @user %>
<div class="body">
  <div class=container>
    <%= flash[:sign_in] %>
    <div class="row">
      <%= render 'layouts/profile', user: @user, book: @book %>
      <div class="col-xs-9">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td></td>
                <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60,  fallback: "no_image.jpg"%></td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
            <%= paginate @users, class: "paginate" %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'layouts/nav', user: @user %>
<div class="body">
  <div class=container>
    <%= flash[:sign_in] %>
    <%= flash[:update] %>
    <div class="row">
      <%= render 'layouts/profile', user: @book_user, book: @book %>
      <div class="col-xs-9">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Body</th>
              <th colspan="3"></th>
            </tr>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60,  fallback: "no_image.jpg"%>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td><%= book.body %></td>
                <td colspan="3"></td>
              </tr>
            <% end %>
            <%= paginate @books, class: "paginate" %>
          </thead>
        </table>
      </div>
    </div>
  </div>
</div>